# The "Good Enough" Makefile where I get things limping.
CFLAGS    = -std=gnu99 -g -Wall
GLFLAGS   = -lGL
SLD2FLAGS = -lSDL2 -lSDL2_image

build:
	gcc -o main.o main.c $(CFLAGS) $(SLD2FLAGS) $(GLFLAGS)
